- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false
  qos_profile: SENSOR_DATA

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: false
  qos_profile: SENSOR_DATA

- ros_topic_name: "/rgb_front/camera_info"
  gz_topic_name: "/rgb_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/rgb_rear/camera_info"
  gz_topic_name: "/rgb_rear/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/rgb_top/camera_info"
  gz_topic_name: "/rgb_top/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/depth_front/camera_info"
  gz_topic_name: "/depth_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/rgb_kuka_palm/camera_info"
  gz_topic_name: "/rgb_kuka_palm/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/depth_kuka_palm/camera_info"
  gz_topic_name: "/depth_kuka_palm/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/range_fr_laser"
  gz_topic_name: "/range_fr_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/range_fl_laser"
  gz_topic_name: "/range_fl_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/range_rr_laser"
  gz_topic_name: "/range_rr_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/range_rl_laser"
  gz_topic_name: "/range_rl_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# - ros_topic_name: "/detections/boxes"
#   gz_topic_name: "/detections/front/boxes"
#   ros_type_name: "vision_msgs/msg/Detection2DArray"
#   gz_type_name: "gz.msgs.AnnotatedAxisAligned2DBox_V"
#   direction: GZ_TO_ROS
#   lazy: true
#   qos_profile: SENSOR_DATA

