/**:
  ros__parameters:
    id_robot: %YOUR_ROBOT_ID_GOES_HERE%
    key: %YOUR_ROBOT_AUTH_KEY_GOES_HERE%
    cloud_bridge_address: %YOUR_BRIDGE_SERVER_ADDRESS% # Bridge Server to connect to, see https://docs.phntm.io/bridge/availability-zones.html
    name: 'Simbot Meredith (Oregon)'
    maintainer_email: 'human@phntm.io' # e-mail for service announcements

    description_header: >
      <a href="https://www.phantomcybernetics.com" id="phntm-cybernetics-logo"><img src="/static/graph/phantom-cybernetics-logo-white.svg"/></a>
      <h2 class="with-phntm-cybernetics-logo">About this Demo</h2>
    description: > # this will be shown as a modal dialog on demo launch
      This simulation utilizes a modified Gazebo Harmonic and runs on a server physically located in Oregon, USA.<br>
      Your RTT depends on geographical distance to the datacenter and your connection quality.<br>
      <br>
      Video is encoded into H.264 using AMD GPU and all data is streamed over WebRTC
      by the <a href="https://docs.phntm.io/bridge" class="external">Phantom Bridge</a>.
      <span class="desktop-only">This UI is responsive and available optimised for mobile devices (phones and tables) on the same URL.</span>
      <span class="touch-only">This UI is responsive and available optimised for desktop on the same URL.</span><br>
      <br>
      <b>Robot Controls</b><br>
      <b class="key-mapping">~</b> enables and disables keyboard control<br>
      Use <b class="key-mapping">E</b>, <b class="key-mapping">D</b>, <b class="key-mapping">S</b>, <b class="key-mapping">F</b>
      and <b class="key-mapping">Left</b> &amp; <b class="key-mapping">Right</b> arrow keys to drive the robot<br>
      You can also connect a gamepad and adjust your mappings in the Human Input Dialog (the monkey in top right).<br>
      On mobile devices you can use the built-in virtual gamepad.<br>
      <br>
      When multiple peers are connected to this robot, you will see a number like <span class="num-peers">2</span> next to the robot's name.
      Too many connected peers may decrease performance. Robot control is allowed to one peer at the time.
      If someone else is driving, you have to wait.<br>
      <br>
      Some features are disabled in this demo, the simulation is restarted every day.<br>
      <br>
      <b>Privacy Disclaimer</b><br>
      This UI uses your browser's local storage to save some data and <a href="https://analytics.google.com" class="external">Google Analytics</a> for traffic monitoring.<br>
      <!-- <input type="checkbox" checked id="map-consent"><label for="map-consent">I AGREE</label></input>
      that my approximate anonymised location will be shown in the <a href="https://map.phntm.io" class="external">Community Map</a> -->

    bridge_server_address: https://us-ca.bridge.phntm.io # Cloud Bridge to connect to, see https://docs.phntm.io/bridge/availability-zones.html
    log_sdp: True # verbose WebRTC debug
    webrtc_debug: True

    extra_packages:
      - vision_msgs

    collapse_services:
      - rcl_interfaces/srv/DescribeParameters
      - rcl_interfaces/srv/GetParameterTypes
      - rcl_interfaces/srv/GetParameters
      - rcl_interfaces/srv/ListParameters
      - rcl_interfaces/srv/SetParameters
      - rcl_interfaces/srv/SetParametersAtomically
      - type_description_interfaces/srv/GetTypeDescription
      - rcl_interfaces/srv/GetLoggerLevels
      - rcl_interfaces/srv/SetLoggerLevels
    collapse_unhandled_services: True

    encoder_default_hw_device: 'vaapi' # 'cuda' for Nvidia, 'vaapi' for AMD/Intel or 'sw' for CPU

    ## Custom topic configs
    /robot_description:
      reliability: RELIABLE # Reliable
      durability: TRANSIENT_LOCAL # Transient local
      lifespan_sec: -1.0 # Infinity
    /tf_static:
      reliability: RELIABLE # Reliable
      durability: TRANSIENT_LOCAL # Transient local
      lifespan_sec: -1.0 # Infinity
    /battery:
      min_voltage: 19.2 # set empty voltage
      max_voltage: 25.2 # set set full voltage
    /rgb_front/camera_info:
      frustum_color: 'lime'
    /rgb_back/camera_info:
      frustum_color: 'red'
    /depth_front/raw:
      max_sensor_value: 2.0
      colormap: 13
    /detections/front/boxes_2d:
      input_width: 128 # detection input frame width
      input_height: 72 # detection input frame height
      label_map: [ 'football', 'mirek works here', 'person', 'woman', 'man', 'camera', 'TV' ] # class label map
    /detections/front/boxes_3d:
      label_map: [ 'football', 'mirek works here', 'person', 'woman', 'man', 'camera', 'TV' ] # class label map
    /detections/back/boxes_2d:
      input_width: 128 # detection input frame width
      input_height: 72 # detection input frame height
      label_map: [ 'football', 'mirek works here', 'person', 'woman', 'man', 'camera', 'TV' ] # class label map
    /detections/back/boxes_3d:
      label_map: [ 'football', 'mirek works here', 'person', 'woman', 'man', 'camera', 'TV' ] # class label map

    ui_battery_topic: '/battery' # battery to show in the UI (e.g. /battery), '' to disable

    ui_wifi_monitor_topic: '/iw_status' # WiFi monitor topic to show in the UI

    # ui_docker_control: True # Docker control via Agent
    docker_monitor_topic: /docker_info # produced by Agent

    ## User input config
    input_drivers: [ 'Twist' ] # enabled input drivers
    input_defaults: /ros2_ws/phntm_input_config.json # path to input config file mounted inside the container