sim_extras_publisher:
  ros__parameters:
    refresh_period_sec: 5.0

    # Battery simulation parameters
    ui_battery_topic: /battery
    nominal_voltage: 22.2
    min_voltage: 19.2
    max_voltage: 25.2
    max_linear_speed: 10.0
    max_angular_speed: 10.0
    voltage_drop_range: 5.0

    # Wi-Fi simulation parameters
    ui_wifi_topic: /iw_status
